### ISSUE TITLE
Multi-channel input/output

### ISSUE THREAD

**Issue by razorx89** [icon-lab/SynDiff#1]
Hey, thanks for this contribution to the scientific community. Could you please add multi-channel support (different for both domains)? I think it should be quite easy to add (define_netG/define_netD have parameters for this), but I haven't had a look at all parts of the code. The dataset loader should also support a 4th dimension for the channels.

Thanks in advance.

**Comment by onat-dalmaz** [comment]
1. The data loader is compatible with multi-input/output channels since the data is in .mat format.
2. Modify the define_netG and define_netD functions to support multi-channel input and output. You can do this by adjusting the input_nc and output_nc variables to match the number of input and output channels.
3. Train the model with multi-channel input and output. You can do this by passing the appropriate values for input_nc and output_nc to the training script.

Once you have made these changes, you should be able to train the model with multi-channel input and output. If you encounter any issues, please ask for further assistance. Good luck!

**Comment by onat-dalmaz** [comment]
We had initially written the code that is only compatible with one-to-one synthesis tasks. Since we only dealt with such tasks in the paper, that was the case. We are planning to release v2.0 of our code soon, which will include training/testing with multi-channel input/outputs.
